tms_payment:
    backends:
        sogenactif:
            parameters:
                pathfile: %payments.sogenactif_pathfile%
        scellius:
            parameters:
                pathfile: %payments.scellius_pathfile%
        paybox:
            parameters:
                keyspath: %payments.paybox_keyspath%
                web_servers:
                    %payments.paybox_web_servers%